-- Credits to ShinyWasabi (https://github.com/YimMenu-Lua/FMTransactionTriggerer/blob/main/service_transactions.lua) for the base. I just modified the transaction list and added some extra stuff.
local service_transactions_tab = gui.get_tab("GUI_TAB_NETWORK"):add_tab("Whole Lotta Money")

local transactions = {
"SERVICE_EARN_JOB_BONUS", -- $15M
"SERVICE_EARN_BEND_JOB", -- $15M
"SERVICE_EARN_CASINO_HEIST_FINALE", -- $3.6M
"SERVICE_EARN_GANGOPS_FINALE", -- $2.55M
"SERVICE_EARN_ISLAND_HEIST_FINALE", -- $2.5M
"SERVICE_EARN_SALVAGE_VEHICLE", -- $2.1M
"SERVICE_EARN_SALVAGE_YARD_SELL_VEH", -- $2.1M
"SERVICE_EARN_TUNER_ROBBERY_FINALE", -- $2M
"SERVICE_EARN_OSCAR_GUZMAN_MISSION", -- $1.08M
"SERVICE_EARN_CHICKEN_FACTORY_RAID_FINALE", -- $1M
"SERVICE_EARN_REFUND_ORBITAL_AUTO", -- $750K
"SERVICE_EARN_REFUND_ORBITAL_MANUAL", -- $500K
"SERVICE_EARN_AMBIENT_JOB_BLAST", -- $300K
"SERVICE_EARN_WINTER_23_AWARD_CHICKEN_FACTORY_RAID", -- $250K
"SERVICE_EARN_FIXER_AWARD_AGENCY_STORY", -- $250K
"SERVICE_EARN_AVENGER_OPS_BONUS", -- $250K
"SERVICE_EARN_AMBIENT_JOB_BEAST", -- $150K
"SERVICE_EARN_BAIL_OFFICE_HIGH_VALUE_PRISONER", -- $150K
"SERVICE_EARN_AMBIENT_JOB_RC_TIME_TRIAL", -- $165K
"SERVICE_EARN_AMBIENT_JOB_BICYCLE_TIME_TRIAL", -- $165K
"SERVICE_EARN_AMBIENT_JOB_PENNED_IN", -- $120K
"SERVICE_EARN_AMBIENT_JOB_KING", -- $120K
"SERVICE_EARN_SIGHTSEEING_REWARD", -- $115K
"SERVICE_EARN_AMBIENT_JOB_XMAS_MUGGER", -- $70K
"SERVICE_EARN_BOSS_AGENCY", -- $60K
"SERVICE_EARN_AMBIENT_JOB_HOT_TARGET_DELIVER", -- $80K
"SERVICE_EARN_AMBIENT_JOB_DEAD_DROP", -- $80K
"SERVICE_EARN_ARENA_CAREER_TIER_PROGRESSION_4", -- $100K
"SERVICE_EARN_AMBIENT_JOB_URBAN_WARFARE", -- $100K
"SERVICE_EARN_AMBIENT_JOB_CHALLENGES", -- $100K
"SERVICE_EARN_AMBIENT_JOB_HOT_PROPERTY", -- $100K
"SERVICE_EARN_AMBIENT_JOB_CLUBHOUSE_CONTRACT", -- $100K
"SERVICE_EARN_AMBIENT_JOB_UNDERWATER_CARGO", -- $100K
"SERVICE_EARN_AMBIENT_JOB_CRIME_SCENE", -- $100K
"SERVICE_EARN_AMBIENT_JOB_METAL_DETECTOR", -- $100K
"SERVICE_EARN_AMBIENT_JOB_SMUGGLER_PLANE", -- $100K
"SERVICE_EARN_AMBIENT_JOB_SMUGGLER_TRAIL", -- $100K
"SERVICE_EARN_AMBIENT_JOB_GOLDEN_GUN", -- $100K
"SERVICE_EARN_AMBIENT_JOB_AMMUNATION_DELIVERY", -- $100K
"SERVICE_EARN_DAILY_STASH_HOUSE_COMPLETED", -- $100K
"SERVICE_EARN_WINTER_22_AWARD_ACID_LAB", -- $100K
"SERVICE_EARN_WINTER_22_AWARD_DAILY_STASH", -- $100K
"SERVICE_EARN_WINTER_22_AWARD_DEAD_DROP", -- $100K
"SERVICE_EARN_WINTER_22_AWARD_RANDOM_EVENT", -- $100K
"SERVICE_EARN_WINTER_22_AWARD_TAXI", -- $100K
"SERVICE_EARN_SMUGGLER_OPS", -- $100K
"SERVICE_EARN_CAYO_ATTRITION_BONUS_OBJECTIVE", -- $100K
"SERVICE_EARN_CHICKEN_FACTORY_RAID_PREP", -- $100K
"SERVICE_EARN_WINTER_23_AWARD_SALVAGE_YARD", -- $100K
"SERVICE_EARN_SALVAGE_YARD_ROBBERY_PREP", -- $100K
"SERVICE_EARN_SALVAGE_YARD_ROBBERY_FINALE", -- $200K
"SERVICE_EARN_AMBIENT_JOB_CHECKPOINT_COLLECTION", -- $200K
"SERVICE_EARN_AMBIENT_JOB_TIME_TRIAL", -- $200K
"SERVICE_EARN_COLLECTABLES_ACTION_FIGURES", -- $200K
"SERVICE_EARN_COLLECTABLE_COMPLETED_COLLECTION", -- $200K
"SERVICE_EARN_TUNER_DAILY_VEHICLE_BONUS", -- $200K
"SERVICE_EARN_ISLAND_HEIST_ELITE_CHALLENGE", -- $200K
"SERVICE_EARN_AMBIENT_JOB_SOURCE_RESEARCH", -- $50K
"SERVICE_EARN_YOHAN_SOURCE_GOODS", -- $50K
"SERVICE_EARN_AMBIENT_JOB_GANG_CONVOY", -- $50K
"SERVICE_EARN_AMBIENT_JOB_SHOP_ROBBERY", -- $50K
"SERVICE_EARN_AMBIENT_JOB_ARMORED_TRUCK", -- $50K
"SERVICE_EARN_AMBIENT_JOB_DRUG_VEHICLE", -- $50K
"SERVICE_EARN_BAIL_OFFICE_PRISONER", -- $50K
"SERVICE_EARN_BOUNTY_HIGH_VALUE_TARGET_GOON", -- $50K
"SERVICE_EARN_ARMS_TRAFFICKING", -- $50K
"SERVICE_EARN_HACKER_DEN_AWARD", -- $50K
"SERVICE_EARN_AMBIENT_JOB_HOT_TARGET_KILL", -- $50K
"SERVICE_EARN_AMBIENT_JOB_HELI_HOT_TARGET", -- $50K
"SERVICE_EARN_AMBIENT_JOB_PASS_PARCEL", -- $50K
"SERVICE_EARN_GOON", -- $50K
"SERVICE_EARN_FROM_BUSINESS_BATTLE", -- $50K
"SERVICE_EARN_ARENA_SKILL_LVL_AWARD", -- $50K
"SERVICE_EARN_ARENA_WAR", -- $50K
"SERVICE_EARN_AMBIENT_JOB_XMAS_TRUCK", -- $40K
"SERVICE_EARN_CASINO_MISSION_REWARD", -- $40K
"SERVICE_EARN_CASINO_HEIST_SETUP_MISSION", -- $40K
"SERVICE_EARN_CASINO_HEIST_PREP_MISSION", -- $40K
"SERVICE_EARN_FROM_FMBB_BOSS_WORK", -- $40K
"SERVICE_EARN_BB_EVENT_BONUS", -- $40K
"SERVICE_EARN_TUNER_DAILY_VEHICLE", -- $40K
"SERVICE_EARN_ACID_LAB_SELL_PARTICIPATION", -- $50K
"SERVICE_EARN_AMBIENT_JOB_TOW_TRUCK_WORK", -- $50K
"SERVICE_EARN_IMPORT_EXPORT", -- $65K
"SERVICE_EARN_JOBS", -- $180K
"SERVICE_EARN_JUGGALO_STORY_MISSION", -- $180K
"SERVICE_EARN_BETTING", -- $680K
"SERVICE_EARN_FROM_VEHICLE_EXPORT", -- $310K
"SERVICE_EARN_SMUGGLER_AGENCY", -- $270K
"SERVICE_EARN_GANGOPS_SETUP", -- $90K
"SERVICE_EARN_CASINO_STORY_MISSION_REWARD", -- $90K
"SERVICE_EARN_BOUNTY_HIGH_VALUE_TARGET_BOSS", -- $100K
"SERVICE_EARN_ARENA_CAREER_TIER_PROGRESSION_3", -- $75K
"SERVICE_EARN_BOUNTY24_DISPATCH_WORK", -- $25K
"SERVICE_EARN_BOUNTY24_PIZZA_DELIVERY", -- $22.5K
"SERVICE_EARN_BOUNTY24_UFO_ABDUCTION", -- $25K
"SERVICE_EARN_BOUNTY24_AWARD", -- $25K
"SERVICE_EARN_FIXER_RIVAL_DELIVERY", -- $25K
"SERVICE_EARN_GANGOPS_PREP_PARTICIPATION", -- $15K
"SERVICE_EARN_GANGOPS_RIVAL_DELIVERY", -- $15K
"SERVICE_EARN_REFUND_HIRE_MERCENARY", -- $22.5K
"SERVICE_EARN_REFUND_HEAD_2_HEAD", -- $30K
"SERVICE_EARN_BOUNTY_COLLECTED", -- $30K
"SERVICE_EARN_FMBB_WAGE_BONUS", -- $30K
"SERVICE_EARN_FIXER_AWARD_SEC_CON", -- $30K
"SERVICE_EARN_REFUND_HIRE_MUGGER", -- $3K
"SERVICE_EARN_REFUND_CLEAR_WANTED", -- $3K
"SERVICE_EARN_ASSASSINATE_TARGET_KILLED", -- $4K
"SERVICE_EARN_REFUNDAMMODROP", -- $5K
"SERVICE_EARN_SERVICE_EARN_PICKUP", -- $10K
"SERVICE_EARN_HOLDUPS", -- $10K
"SERVICE_EARN_REFUND_HELI_PICKUP", -- $10K
"SERVICE_EARN_GANGATTACK_PICKUP", -- $10K
"SERVICE_EARN_FROM_DESTROYING_CONTRABAND", -- $10K
"SERVICE_EARN_WAGE_PAYMENT_BONUS", -- $10K
"SERVICE_EARN_WAGE_PAYMENT", -- $10K
"SERVICE_EARN_AMBIENT_MUGGING", -- $10K
"SERVICE_EARN_DEATHMATCH_BOUNTY", -- $10K
"SERVICE_EARN_NCLUB_TROUBLEMAKER", -- $10K
"SERVICE_EARN_DAILY_STASH_HOUSE_PARTICIPATION", -- $10K
"SERVICE_EARN_HACKER_ROBBERY_PREP", -- $10K
"SERVICE_EARN_BOUNTY_STANDARD_TARGET_GOON", -- $10K
"SERVICE_EARN_REFUND_BUY_CARDROPOFF", -- $1.5K
"SERVICE_EARN_CASHING_OUT", -- $1.5K
"SERVICE_EARN_SALVAGE_CHECKPOINT_COLLECTION", -- $1K
"SERVICE_EARN_REFUND_BOAT_PICKUP", -- $750
"SERVICE_EARN_REFUND_ARENA_SPEC_BOX_ENTRY", -- $100
"SERVICE_EARN_NOT_BADSPORT", -- $2K
"SERVICE_EARN_AMBIENT_PICKUP", -- $2K
"SERVICE_EARN_COLLECTABLES_SIGNAL_JAMMERS", -- $2K
"SERVICE_EARN_DAILY_OBJECTIVES", -- Depends.
"SERVICE_EARN_WEEKLY_OBJECTIVE_COMPLETED", -- Depends.
}

gui.show_message("Whole Lotta Money", "Successfully initialized.")
gui.show_message("Whole Lotta Money", "ONLY run this every 1-2 minutes. You'll most likely get banned eitherway but just incase.")

service_transactions_tab:add_imgui(function()
    if not network.is_session_started() or not script.is_active("shop_controller") then
        ImGui.Text("Please join GTA Online.")
        return
    end

    if ImGui.Button("Add Money (~$50M)") then
        gui.show_message("Whole Lotta Money", "Executing transactions. This could take anywhere from 1-3 minutes.")
        script.run_in_fiber(function(script)
            for i, transaction in ipairs(transactions) do
                if NETSHOPPING.NET_GAMESERVER_USE_SERVER_TRANSACTIONS() then
                    local hash  = joaat(transaction)
                    local price = NETSHOPPING.NET_GAMESERVER_GET_PRICE(hash, joaat("CATEGORY_SERVICE_WITH_THRESHOLD"), true)
                    local index = memory.allocate(4)
                    
                    if NETSHOPPING.NET_GAMESERVER_CATALOG_ITEM_KEY_IS_VALID(hash) then
                        scr_function.call_script_function("shop_controller", "FST", "2D 06 09 00 00 5D ? ? ? 06", "void", {
                            { "int", hash   },
                            { "int", price  },
                            { "ptr", index  },
                            { "bool", true  }, -- Money to bank. Set to true/false.
                            { "bool", false }, -- Money to wallet. Set to true/false.
                            { "bool", false } -- Unknown bool, testing needed.
                        })
                        memory.free(index)
                        script:sleep(500)
                        
                        if globals.get_int(4538089) ~= 1 then
                            log.info(transaction .. " Transaction Successful.")
                        else
                            log.error(transaction .. " Transaction Failed.")
                            globals.set_int(4538089, 0)
                        end
                    end
                else
                    gui.show_error("Whole Lotta Money", "Couldn't trigger transaction.")
                    break
                end
            end
            gui.show_message("Whole Lotta Money", "Done. You might not get money from every transaction, but that's part of the game.")
        end)
    end
end)
